### ISSUE TITLE
Fails on German locale

### ISSUE THREAD

**Issue by andk** [barefootcoder/perlx-bash#2]
As per subject. Probably best illustrated with this table:

http://analysis.cpantesters.org/reports_by_field?distv=PerlX-bash-0.01;field=env%3ALC_ALL;order=2ta

because the table grows with time. At the moment it shows that exactly every report that has LC_ALL matching /^de/ leads to a fail. We will see how it develops.

**Comment by barefootcoder** [comment]
Thanks Andreas.  I had noticed that, but I haven't quite wrapped my head around how to fix it yet.  I want to make sure that I'm getting the right error—passing when there's any error at all seems like just asking for trouble—but I'm not sure how to handle that in the face of i18n.

Also curious that it only seems to be the German locale that triggers it ... one would think that any non-English locale would do it.

**Comment by andk** [comment]
>>>>> On Sun, 10 Dec 2017 01:40:39 -0800, Buddy Burden <notifications@github.com> said:

  > I'm not sure how to handle that in the face of i18n.

I'd just set the locale to C for the tests.

  > Also curious that it only seems to be the German locale that triggers
  > it ... one would think that any non-English locale would do it.

It fails for other locales too, but it's not very common that people
test with other locales. I let my smoker test two more locales right
after I reported this one, so in a few hours or days you will see other
locales appearing on that page.

-- 
andreas

**Comment by barefootcoder** [comment]
> I'd just set the locale to C for the tests.

Oh, yeah ... duh.  Thx for pointing that out to me; obviously I was missing the obvious there.  I suppose just sticking something like this—`$ENV{LC_ALL} = 'C';`—up above the test should do it, right?

> It fails for other locales too, but it's not very common that people test with other locales.

Ah.  Well, good that you're planning to run a few more then. :-)

I'm also going to see if I can eliminate the failures when there is no `bash` at all (e.g. Windows); the next version should be much cleaner.

Thx again for the help!

**Comment by barefootcoder** [comment]
CPANTesters has 100% pass rate with this new version, so I'd say the fix worked.  I'm resolving this and promoting my dev version to official.
